simulator_type: libero
task_suite_name: libero_goal

auto_reset: ${algorithm.auto_reset}
ignore_terminations: ${algorithm.ignore_terminations}
max_episode_steps: 512

use_rel_reward: True
reward_coef: 5.0
only_eval: False

seed: 0
num_group: ${algorithm.num_group_envs}
group_size: ${algorithm.group_size}
use_fixed_reset_state_ids: ${algorithm.use_fixed_reset_state_ids}
num_images_in_input: 1

num_envs: ${multiply:${algorithm.group_size}, ${algorithm.num_group_envs}}

video_cfg:
  save_video: True
  info_on_video: True
  video_base_dir: ${runner.logger.log_path}/video/train

init_params:
  camera_heights: 256
  camera_widths: 256