defaults:
  - override hydra/job_logging: stdout

hydra:
  run:
    dir: .
  output_subdir: null

cluster:
  num_nodes: 16
  num_gpus_per_node: 8
  component_placement:
    actor,rollout: all

runner:
  task_type: math
  logger:
    log_path: ${runner.output_dir}/${runner.experiment_name}
    project_name: rlinf
    experiment_name: ${runner.experiment_name}
    logger_backends: ["tensorboard"] # wandb, swanlab

  max_epochs: 5
  max_steps: -1

  val_check_interval: 1
  save_interval: 50

  seq_length: 28672

  enable_dynamic_batch_size: False
  max_tokens_per_mbs: 28672

  resume_dir: null
  experiment_name: grpo-7b
  output_dir: ../results

algorithm:
  group_size: 16

  n_minibatches: 4
  training_batch_size_per_gpu: 1 # micro batch size
  rollout_batch_size_per_gpu: null # If set to null, rollout_batch_size will be evenly divided across all inference instances. You can reduce this parameter if inference consumes too much GPU memory.

  # mbs to do log prob inference, can be set to
  # lower than rollout_batch_size_per_gpu to reduce
  # memory usage
  logprob_forward_micro_batch_size: 1 # ${.rollout_batch_size_per_gpu}

  # val rollout mbs
  val_rollout_batch_size_per_gpu: 4 # ${.rollout_batch_size_per_gpu}

  shuffle_rollout: True

  # GRPO loss params
  loss_type: ppo
  loss_agg_func: "token-mean" # "seq-mean-token-sum"
  kl_beta: 0.0 # 0.001
  kl_penalty_type: low_var_kl
  ratio_clip_eps: 0.2
  entropy_bonus: 0.0
  calculate_entropy: False
  clip_ratio_c: null # 3.0

  adv_type: grpo
  normalize_advantages: True
  early_stop_imp_ratio: 5.0
  use_valid_token_scale: True

  # params for rollout
  sampling_params:
    use_greedy: False
    temperature: 1.0
    top_k: 1000000
    top_p: 1.0
    repetition_penalty: 1.0
    max_new_tokens: ${subtract:${runner.seq_length}, ${data.max_prompt_length}}
    min_new_tokens: 1

rollout:
  group_name: "RolloutGroup"

  gpu_memory_utilization: 0.65

  model_dir: /model/DeepSeek-R1-Distill-Qwen-7B
  model_arch: qwen2.5
  enforce_eager: False         # if False, vllm will capture cuda graph, which will take more time to initialize.
  distributed_executor_backend: mp   # ray or mp
  disable_log_stats: False
  detokenize: False            # Whether to detokenize the output. During RL we actually don't need to detokenize it. Can be set to True for debugging.
  padding: null               # will be tokenizer.pad_token_id if null. it is used to filter megatron's padding for vllm rollout
  eos: null                   # will be tokenizer.eos_token_id if null.

  attention_backend: triton
  recompute_logprobs: True

  tensor_parallel_size: 2
  pipeline_parallel_size: 1
  
  validate_weight: False # whether to send all weights at first for weight comparison.
  validate_save_dir: null # the directory to save the weights for comparison. If validate_weight is True, this will be used to save the weights for comparison.
  print_outputs: False         # whether to print the outputs (token ids, texts, etc.) of inference engine.

  sglang_decode_log_interval: 5000 # the interval for SGLang to log the decode time and other stats.
  max_running_requests: 64 # the maximum number of running requests in the inference engine.
  cuda_graph_max_bs: 128 # the maximum batch size for cuda graph. If the batch size is larger than this, cuda graph will not be used.

  use_torch_compile: False # enable torch_compile in SGLang for rollout.
  torch_compile_max_bs: 128 # the maximum batch size for torch compile. If the batch size is larger than this, torch compile will not be used.

data:
  type: math
  max_prompt_length: 1024
  rollout_batch_size: 512
  val_rollout_batch_size: null
  num_workers: 2
  prompt_key: prompt
  shuffle: True
  validation_shuffle: True
  seed: 1234
  train_data_paths: ["/dataset/boba/AReaL-boba-106k.jsonl"]
  val_data_paths: ["/dataset/boba/AReaL-boba-106k.jsonl"]

actor:
  group_name: "ActorGroup"
  training_backend: megatron
  mcore_gpt: True
  spec_name: decoder_gpt

  checkpoint_load_path: null

  offload_optimizer: True
  offload_weight: True
  offload_grad: True
  enable_dp_load_balance: False

  calculate_flops: False

  seed: 1234

  model:
    precision: fp16
    add_bias_linear: False

    tensor_model_parallel_size: 4
    pipeline_model_parallel_size: 1

    activation: swiglu
    sequence_parallel: True
    # recompute_method: block
    # recompute_granularity: selective

    recompute_method: block
    recompute_granularity: full
    recompute_num_layers: 20

    seq_length: ${runner.seq_length}
    encoder_seq_length: ${runner.seq_length}

    normalization: rmsnorm

    position_embedding_type: rope

    apply_rope_fusion: True
    bias_dropout_fusion: False
    persist_layer_norm: False
    bias_activation_fusion: False
    attention_softmax_in_fp32: True
    batch_p2p_comm: False
    variable_seq_lengths: True
    gradient_accumulation_fusion: False
    moe_token_dispatcher_type: alltoall
    use_cpu_initialization: False

  optim:
    optimizer: adam
    bf16: False
    fp16: True
    lr: 2e-05
    adam_beta1: 0.9
    adam_beta2: 0.95
    adam_eps: 1.0e-05
    min_lr: 2.0e-6
    weight_decay: 0.05
    use_distributed_optimizer: True
    overlap_grad_reduce: True
    overlap_param_gather: True
    optimizer_enable_pin: false
    overlap_param_gather_with_optimizer_step: False
    clip_grad: 1.0
    loss_scale_window: 5
    
  lr_sched:

    lr_warmup_fraction: 0.005
    lr_warmup_init: 0.0
    lr_warmup_iters: 5
    max_lr: 2.0e-5
    min_lr: 2.0e-6
    lr_decay_style: cosine
    lr_decay_iters: 5000
    start_weight_decay: 0.0
    end_weight_decay: 0.1
    weight_decay_incr_style: cosine

  tokenizer:
    tokenizer_model: /model/DeepSeek-R1-Distill-Qwen-7B
    use_fast: False
    trust_remote_code: True
    padding_side: 'right'

  megatron:
    ddp_bucket_size: null
    distributed_backend: nccl # Support 'nccl' and 'gloo'
    distributed_timeout_minutes: 30
    ckpt_format: torch
    use_dist_ckpt: False
    tp_comm_bootstrap_backend: nccl
    tp_comm_overlap_cfg: null # tp_comm_overlap_cfg.yaml
    use_hf_ckpt: False # if true, will transfer hf model to generate megatron checkpoint and use it for training.
    
    ckpt_convertor: # config for ckpt convertor
      model: DeepSeek-R1-Distill-Qwen-7B
      model_type: null # will be set by hf model's config if null
      hf_model_path: ${rollout.model_dir} # path to the hf model
      save_path: ${runner.output_dir}/${runner.experiment_name}/converted_ckpts/actor
      use_gpu_num : 0
      use_gpu_index: null
      process_num: 16 # number of processes to use for checkpointing
      tensor_model_parallel_size: ${actor.model.tensor_model_parallel_size}
      pipeline_model_parallel_size: ${actor.model.pipeline_model_parallel_size}

reward:
  use_reward_model: false
  reward_type: 'math'
  reward_scale: 5.0

critic:
  use_critic_model: false