name: Math End2End Rollout Logprobs

on:
    push:
        branches:
          - 'release/v[0-9].[0-9]'
          - main
        paths:
          - '**/*.py'
          - 'tests/**'
          - '.github/workflows/*.yml'
          - '!docs/**'
          - '!README.md'
          - '!*.yaml'
          - '!*.toml'
          - '!ray_utils/**'
          - '!requirements/**'

    pull_request:
        branches:
          - 'release/v[0-9].[0-9]'
          - main
        paths:
          - '**/*.py'
          - 'tests/**'
          - '.github/workflows/*.yml'
          - '!docs/**'
          - '!README.md'
          - '*.yaml'
          - '*.toml'
          - '!ray_utils/**'
          - '!requirements/**'

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
    qwen-grpo-test:
        runs-on: rlinf
        container:
            image: rlinf/rlinf:math-rlinf0.1-torch2.6.0-sglang0.4.6.post5-vllm0.8.5-megatron0.13.0-te2.1
            volumes:
                - /mnt/public/dataset:/workspace/dataset
                - /mnt/public/tokenizer:/workspace/tokenizer
            options: --gpus="all" --shm-size=80g

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: SGLang Collocated mode
              run: |
                export REPO_PATH=$(pwd)
                bash tests/e2e_tests/math/sglang/run_collocated.sh qwen2.5-1.5b-grpo-collocated-rollout-logprobs.yaml

            - name: vLLM Collocated mode
              run: |
                export REPO_PATH=$(pwd)
                bash tests/e2e_tests/math/vllm/run_collocated.sh qwen2.5-1.5b-grpo-collocated-rollout-logprobs.yaml

            - name: SGLang Pipeline mode
              run: |
                export REPO_PATH=$(pwd)
                bash tests/e2e_tests/math/sglang/run_pipeline.sh qwen2.5-1.5b-grpo-pipeline-rollout-logprobs.yaml
